# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Davids Blog
tagline:          'A blog'
description:      'David Grossmans Thoughts'
url:              http://2gotgrossman.github.com
baseurl:          /

author:
  name:           'David Grossman'
  url:            https://github.com/2gotgrossman

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/2gotgrossman
