# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            David's Blog
tagline:          'Thoughts on life, liberty and the pursuit of good software design'
description:      ''
url:              http://2gotgrossman.github.com
baseurl:          /

author:
  name:           'David Grossman'
  url:            https://github.com/2gotgrossman

paginate:         5

# Custom vars
version:          2.1.0

